
all: ../../manuscript/figures/figure-1.pdf ../../manuscript/figures/figure-2.pdf ../../manuscript/figures/figure-3.pdf

../../manuscript/figures/figure-1.pdf: figure-1.pdf
		cp figure-1.pdf ../../manuscript/figures/figure-1.pdf

../../manuscript/figures/figure-2.pdf: figure-2.pdf
		cp figure-2.pdf ../../manuscript/figures/figure-2.pdf

../../manuscript/figures/figure-3.pdf: figure-3.pdf
		cp figure-3.pdf ../../manuscript/figures/figure-3.pdf


