all: ../../manuscript/figures/figure-1.pdf ../../manuscript/figures/figure-2.pdf ../../manuscript/figures/figure-3.pdf \
	../../manuscript/figures/barghi-correction-plot.pdf ../../manuscript/figures/barghi-offset-panels.pdf \
	../../manuscript/figures/barghi-tailprobs-panels.pdf ../../manuscript/figures/barghi-offset-replicate-panels.pdf \
	../../manuscript/figures/barghi-cross-validation-binsize.pdf ../../manuscript/figures/barghi-tailprobs-seqid-20.pdf \
  ../../manuscript/figures/bergland-pvalue-comparison.pdf ../../manuscript/figures/bergland-pvalue-comparison.png \
	../../manuscript/figures/bergland-pvalue-permutation-hist.pdf ../../manuscript/figures/bergland_pvalues.pdf \
  ../../manuscript/figures/bergland-correction-plot.pdf ../../manuscript/figures/bergland-covs-figure.pdf \
   ../../manuscript/figures/bergland-combined-hists.pdf ../../manuscript/figures/barghi-cov-panels.pdf \
   ../../manuscript/figures/castro_rep_cis.pdf

../../manuscript/figures/figure-1.pdf: figure-1.pdf
		cp figure-1.pdf ../../manuscript/figures/figure-1.pdf

../../manuscript/figures/figure-2.pdf: figure-2.pdf
		cp figure-2.pdf ../../manuscript/figures/figure-2.pdf

../../manuscript/figures/figure-3.pdf: figure-3.pdf
		cp figure-3.pdf ../../manuscript/figures/figure-3.pdf

../../manuscript/figures/barghi-correction-plot.pdf: barghi-correction-plot.pdf
		cp $< $@

../../manuscript/figures/barghi-offset-panels.pdf: barghi-offset-panels.pdf
		cp $< $@

../../manuscript/figures/barghi-tailprobs-panels.pdf: barghi-tailprobs-panels.pdf
		cp $< $@

../../manuscript/figures/barghi-offset-replicate-panels.pdf: barghi-offset-replicate-panels.pdf
		cp $< $@

../../manuscript/figures/barghi-cross-validation-binsize.pdf: barghi-cross-validation-binsize.pdf
		cp $< $@

../../manuscript/figures/barghi-tailprobs-seqid-20.pdf: barghi-tailprobs-seqid-20.pdf
		cp $< $@

../../manuscript/figures/bergland-pvalue-comparison.pdf: bergland-pvalue-comparison.pdf
		cp $< $@

../../manuscript/figures/bergland-pvalue-comparison.png: bergland-pvalue-comparison.png
		cp $< $@

../../manuscript/figures/bergland-pvalue-permutation-hist.pdf: bergland-pvalue-permutation-hist.pdf
		cp $< $@

../../manuscript/figures/bergland_pvalues.pdf: bergland_pvalues.pdf
		cp $< $@

../../manuscript/figures/bergland-correction-plot.pdf: bergland-correction-plot.pdf
		cp $< $@

../../manuscript/figures/bergland-covs-figure.pdf: bergland-covs-figure.pdf
		cp $< $@

../../manuscript/figures/bergland-combined-hists.pdf: bergland-combined-hists.pdf
		cp $< $@

../../manuscript/figures/barghi-cov-panels.pdf: barghi-cov-panels.pdf
		cp $< $@

../../manuscript/figures/castro_rep_cis.pdf: castro_rep_cis.pdf
		cp $< $@
